#include "hmg.ch"
#include "hbclass.ch"

#define TDZ_TRUE .T.

// Usado TConhecimento e Não "TCTe" para não conflitir com os objetos da lib xml sefaz CTe, CTes
class TConhecimento

    data id readonly
    data emp_id readonly
    data versao_xml readonly
    data dhEmi readonly
    data modelo readonly
    data serie readonly
    data nCT readonly
    data cCT readonly
    data situacao readonly
    data chCTe readonly
    data nProt readonly
    data CFOP readonly
    data natOp readonly
    data tpEmis readonly
    data tpCTe readonly
    data modal readonly
    data tpServ readonly
    data cMunIni readonly
    data xMunIni readonly
    data UFIni readonly
    data cMunFim readonly
    data xMunFim readonly
    data UFFim readonly
    data retira readonly
    data xDetRetira readonly
    data clie_tomador_id readonly
    data indIEToma readonly
    data tom_ie_isento readonly
    data tomador readonly
    data tom_cnpj readonly
    data tom_ie readonly
    data tom_cpf readonly
    data tom_xFant readonly
    data tom_xNome readonly
    data tom_fone readonly
    data tom_end_logradouro readonly
    data tom_end_numero readonly
    data tom_end_complemento readonly
    data tom_end_bairro readonly
    data tom_cid_codigo_municipio readonly
    data tom_cid_municipio readonly
    data tom_end_cep readonly
    data tom_cid_uf readonly
    data xCaracAd readonly
    data xCaracSer readonly
    data xEmi readonly
    data xOrig readonly
    data xPass readonly
    data xDest readonly
    data tpPer readonly
    data dProg readonly
    data dIni readonly
    data dFim readonly
    data tpHor readonly
    data hProg readonly
    data hIni readonly
    data hFim readonly
    data xObs readonly
    data clie_remetente_id readonly
    data rem_razao_social readonly
    data rem_nome_fantasia readonly
    data rem_cnpj readonly
    data rem_ie readonly
    data rem_cpf readonly
    data rem_fone readonly
    data rem_end_logradouro readonly
    data rem_end_numero readonly
    data rem_end_complemento readonly
    data rem_end_bairro readonly
    data rem_cid_codigo_municipio readonly
    data rem_cid_municipio readonly
    data rem_end_cep readonly
    data rem_cid_uf readonly
    data rem_icms readonly
    data clie_destinatario_id readonly
    data des_razao_social readonly
    data des_nome_fantasia readonly
    data des_cnpj readonly
    data des_ie readonly
    data des_cpf readonly
    data des_fone readonly
    data des_end_logradouro readonly
    data des_end_numero readonly
    data des_end_complemento readonly
    data des_end_bairro readonly
    data des_cid_codigo_municipio readonly
    data des_cid_municipio readonly
    data des_end_cep readonly
    data des_cid_uf readonly
    data des_icms readonly
    data clie_expedidor_id readonly
    data exp_razao_social readonly
    data exp_nome_fantasia readonly
    data exp_cnpj readonly
    data exp_ie readonly
    data exp_cpf readonly
    data exp_fone readonly
    data exp_end_logradouro readonly
    data exp_end_numero readonly
    data exp_end_complemento readonly
    data exp_end_bairro readonly
    data exp_cid_codigo_municipio readonly
    data exp_cid_municipio readonly
    data exp_end_cep readonly
    data exp_cid_uf readonly
    data exp_icms readonly
    data clie_recebedor_id readonly
    data rec_razao_social readonly
    data rec_nome_fantasia readonly
    data rec_cnpj readonly
    data rec_ie readonly
    data rec_cpf readonly
    data rec_fone readonly
    data rec_end_logradouro readonly
    data rec_end_numero readonly
    data rec_end_complemento readonly
    data rec_end_bairro readonly
    data rec_cid_codigo_municipio readonly
    data rec_cid_municipio readonly
    data rec_end_cep readonly
    data rec_cid_uf readonly
    data rec_icms readonly
    data vTPrest readonly
    data vBC readonly
    data pICMS readonly
    data vICMS readonly
    data pRedBC readonly
    data vCred readonly
    data codigo_sit_tributaria readonly
    data vPIS readonly
    data vCOFINS readonly
    data vTotTrib readonly
    data infAdFisco readonly
    data vCarga readonly
    data proPred readonly
    data cTar readonly
    data xOutCat readonly
    data peso_bruto readonly
    data peso_cubado readonly
    data peso_bc readonly
    data cubagem_m3 readonly
    data qtde_volumes readonly
    data tipo_doc_anexo readonly
    data nOCA readonly
    data dPrevAereo readonly
    data monitor_action readonly

    method new(cte) constructor

end class

method new(cte) class TConhecimento

    ::id := cte["id"]
    ::emp_id := cte["emp_id"]
    ::versao_xml := cte["versao_xml"]
    ::dhEmi := string_as_DateTime(cte["dhEmi"], TDZ_TRUE)
    ::modelo := cte["modelo"]
    ::serie := cte["serie"]
    ::nCT := cte["nCT"]
    ::cCT := cte["cCT"]
    ::situacao := cte["situacao"]
    ::chCTe := cte["chCTe"]
    ::nProt := cte["nProt"]
    ::CFOP := cte["CFOP"]
    ::natOp := cte["natOp"]
    ::tpEmis := cte["tpEmis"]
    ::tpCTe := cte["tpCTe"]
    ::modal := cte["modal"]
    ::tpServ := cte["tpServ"]
    ::cMunIni := cte["cMunIni"]
    ::xMunIni := cte["xMunIni"]
    ::UFIni := cte["UFIni"]
    ::cMunFim := cte["cMunFim"]
    ::xMunFim := cte["xMunFim"]
    ::UFFim := cte["UFFim"]
    ::retira := cte["retira"]
    ::xDetRetira := cte["xDetRetira"]
    ::clie_tomador_id := cte["clie_tomador_id"]
    ::indIEToma := cte["indIEToma"]
    ::tom_ie_isento := cte["tom_ie_isento"]
    ::tomador := cte["tomador"]
    ::tom_cnpj := getNumbers(cte["tom_cnpj"])
    ::tom_ie := cte["tom_ie"]
    ::tom_cpf := getNumbers(cte["tom_cpf"])
    ::tom_xFant := cte["tom_xFant"]
    ::tom_xNome := cte["tom_xNome"]
    ::tom_fone := getNumbers(cte["tom_fone"])
    ::tom_end_logradouro := cte["tom_end_logradouro"]
    ::tom_end_numero := cte["tom_end_numero"]
    ::tom_end_complemento := cte["tom_end_complemento"]
    ::tom_end_bairro := cte["tom_end_bairro"]
    ::tom_cid_codigo_municipio := cte["tom_cid_codigo_municipio"]
    ::tom_cid_municipio := cte["tom_cid_municipio"]
    ::tom_end_cep := getNumbers(cte["tom_end_cep"])
    ::tom_cid_uf := cte["tom_cid_uf"]
    ::xCaracAd := cte["xCaracAd"]
    ::xCaracSer := cte["xCaracSer"]
    ::xEmi := cte["xEmi"]
    ::xOrig := cte["xOrig"]
    ::xPass := cte["xPass"]
    ::xDest := cte["xDest"]
    ::tpPer := cte["tpPer"]
    ::dProg := date_as_string(cte["dProg"])
    ::dIni := date_as_string(cte["dIni"])
    ::dFim := date_as_string(cte["dFim"])
    ::tpHor := cte["tpHor"]
    ::hProg := cte["hProg"]
    ::hIni := cte["hIni"]
    ::hFim := cte["hFim"]
    ::xObs := cte["xObs"]
    ::clie_remetente_id := cte["clie_remetente_id"]
    ::rem_razao_social := cte["rem_razao_social"]
    ::rem_nome_fantasia := cte["rem_nome_fantasia"]
    ::rem_cnpj := getNumbers(cte["rem_cnpj"])
    ::rem_ie := cte["rem_ie"]
    ::rem_cpf := getNumbers(cte["rem_cpf"])
    ::rem_fone := getNumbers(cte["rem_fone"])
    ::rem_end_logradouro := cte["rem_end_logradouro"]
    ::rem_end_numero := cte["rem_end_numero"]
    ::rem_end_complemento := cte["rem_end_complemento"]
    ::rem_end_bairro := cte["rem_end_bairro"]
    ::rem_cid_codigo_municipio := cte["rem_cid_codigo_municipio"]
    ::rem_cid_municipio := cte["rem_cid_municipio"]
    ::rem_end_cep := getNumbers(cte["rem_end_cep"])
    ::rem_cid_uf := cte["rem_cid_uf"]
    ::rem_icms := cte["rem_icms"]
    ::clie_destinatario_id := cte["clie_destinatario_id"]
    ::des_razao_social := cte["des_razao_social"]
    ::des_nome_fantasia := cte["des_nome_fantasia"]
    ::des_cnpj := getNumbers(cte["des_cnpj"])
    ::des_ie := cte["des_ie"]
    ::des_cpf := getNumbers(cte["des_cpf"])
    ::des_fone := getNumbers(cte["des_fone"])
    ::des_end_logradouro := cte["des_end_logradouro"]
    ::des_end_numero := cte["des_end_numero"]
    ::des_end_complemento := cte["des_end_complemento"]
    ::des_end_bairro := cte["des_end_bairro"]
    ::des_cid_codigo_municipio := cte["des_cid_codigo_municipio"]
    ::des_cid_municipio := cte["des_cid_municipio"]
    ::des_end_cep := getNumbers(cte["des_end_cep"])
    ::des_cid_uf := cte["des_cid_uf"]
    ::des_icms := cte["des_icms"]
    ::clie_expedidor_id := cte["clie_expedidor_id"]
    ::exp_razao_social := cte["exp_razao_social"]
    ::exp_nome_fantasia := cte["exp_nome_fantasia"]
    ::exp_cnpj := getNumbers(cte["exp_cnpj"])
    ::exp_ie := cte["exp_ie"]
    ::exp_cpf := getNumbers(cte["exp_cpf"])
    ::exp_fone := getNumbers(cte["exp_fone"])
    ::exp_end_logradouro := cte["exp_end_logradouro"]
    ::exp_end_numero := cte["exp_end_numero"]
    ::exp_end_complemento := cte["exp_end_complemento"]
    ::exp_end_bairro := cte["exp_end_bairro"]
    ::exp_cid_codigo_municipio := cte["exp_cid_codigo_municipio"]
    ::exp_cid_municipio := cte["exp_cid_municipio"]
    ::exp_end_cep := getNumbers(cte["exp_end_cep"])
    ::exp_cid_uf := cte["exp_cid_uf"]
    ::exp_icms := cte["exp_icms"]
    ::clie_recebedor_id := cte["clie_recebedor_id"]
    ::rec_razao_social := cte["rec_razao_social"]
    ::rec_nome_fantasia := cte["rec_nome_fantasia"]
    ::rec_cnpj := getNumbers(cte["rec_cnpj"])
    ::rec_ie := cte["rec_ie"]
    ::rec_cpf := getNumbers(cte["rec_cpf"])
    ::rec_fone := getNumbers(cte["rec_fone"])
    ::rec_end_logradouro := cte["rec_end_logradouro"]
    ::rec_end_numero := cte["rec_end_numero"]
    ::rec_end_complemento := cte["rec_end_complemento"]
    ::rec_end_bairro := cte["rec_end_bairro"]
    ::rec_cid_codigo_municipio := cte["rec_cid_codigo_municipio"]
    ::rec_cid_municipio := cte["rec_cid_municipio"]
    ::rec_end_cep := getNumbers(cte["rec_end_cep"])
    ::rec_cid_uf := cte["rec_cid_uf"]
    ::rec_icms := cte["rec_icms"]
    ::vTPrest := cte["vTPrest"]
    ::vBC := cte["vBC"]
    ::pICMS := cte["pICMS"]
    ::vICMS := cte["vICMS"]
    ::pRedBC := cte["pRedBC"]
    ::vCred := cte["vCred"]
    ::codigo_sit_tributaria := cte["codigo_sit_tributaria"]
    ::vPIS := cte["vPIS"]
    ::vCOFINS := cte["vCOFINS"]
    ::vTotTrib := cte["vTotTrib"]
    ::infAdFisco := cte["infAdFisco"]
    ::vCarga := cte["vCarga"]
    ::proPred := cte["proPred"]
    ::cTar := cte["cTar"]
    ::xOutCat := cte["xOutCat"]
    ::peso_bruto := cte["peso_bruto"]
    ::peso_cubado := cte["peso_cubado"]
    ::peso_bc := cte["peso_bc"]
    ::cubagem_m3 := cte["cubagem_m3"]
    ::qtde_volumes := cte["qtde_volumes"]
    ::tipo_doc_anexo := cte["tipo_doc_anexo"]
    ::nOCA := cte["nOCA"]
    ::dPrevAereo := date_as_string(cte["dPrevAereo"])
    ::monitor_action := cte["monitor_action"]
return self
